[package]
name = "ar_proj_server"
version = "0.1.0"
authors = ["Tucker Morgan <tucker.bull.morgan@gmail.com>", "Gavriel Rachael-Homann <gavrielrachaelhomann@gmail.com>"]

[dependencies]
serde_json = "1.0"